version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build Docker image
          command: docker build -t nodewebapp .
      - run:
          name: Push Docker image
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push nodewebapp
  deploy:
    docker:
      - image: circleci/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to Kubernetes
          command: |
            aws eks update-kubeconfig --region your-aws-region --name your-eks-cluster-name
            kubectl apply -f deployment.yaml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
